# Copyright (C) 1994 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += wchar.c
SRC += wcwidth.c
SRC += wmemcpy.c
SRC += wmemchr.c
SRC += wcslen.c
SRC += wcsnlen.c
SRC += wcsrtombs.c
SRC += wcsnrtombs.c

include $(TOP)/../makefile.inc
