.\" -*- nroff -*-  (This is for Emacs)
.TH dj64-gcc 1 "2024-06-13" "Version 0.1" "Development"
.SH NAME
dj64-gcc \- cross-compile 64-bit DOS programs
.SH SYNOPSIS
.B dj64-gcc
[
.B gcc_opts
]
.B -o <out_file>.o
.B -c <in_file>.[cSs]
.PP
.SH DESCRIPTION
.B dj64-gcc
compiles the C or assembler source files into an intermediate object files.
It is used by dj64-provided
.I dj64.mk
makefile hook and should not be called directly. The intermediate object
files compiled with
.I dj64-gcc
are further processed in
.I dj64.mk
and you get a different object files as an output.

.SH "EXAMPLES"
.TP
dj64-gcc -Wall -Os -ggdb3 -DREV=\\"0.1\\" -I. -o command.o -c command.c
.TP
dj64-gcc -o asm.o -c asm.S

.SH "NOTES"
You may want to use
.I dj64-gcc
directly only if you use non-make-based build system, like meson.

You can't freely reorder command-line arguments. Please use the order
specified in this man page.

.SH "AUTHOR"
.TP
stsp2@yandex.ru (@stsp on github)
