# Copyright (C) 2003 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += access.c
SRC += alarm.c
SRC += chdir.c
SRC += chown.c
SRC += close.c
SRC += confstr.c
SRC += ctermid.c
SRC += dup.c
SRC += dup2.c
SRC += execl.c
SRC += execle.c
SRC += execlp.c
SRC += execlpe.c
SRC += execv.c
SRC += execve.c
SRC += execvp.c
SRC += execvpe.c
SRC += fchdir.c
SRC += fork.c
SRC += fpathcon.c
SRC += getcwd.c
SRC += getegid.c
SRC += geteuid.c
SRC += getgid.c
SRC += getgroup.c
SRC += getlogin.c
SRC += getopt.c
SRC += getpgrp.c
SRC += getpid.c
SRC += getppid.c
SRC += getuid.c
SRC += isatty.c
SRC += link.c
SRC += lseek.c
SRC += pathconf.c
SRC += pause.c
SRC += pipe.c
SRC += pwrite.c
SRC += read.c
SRC += rmdir.c
SRC += setgid.c
SRC += setpgid.c
SRC += setsid.c
SRC += setuid.c
SRC += sleep.c
SRC += sysconf.c
SRC += ttyname.c
SRC += unlink.s
SRC += write.c

include $(TOP)/../makefile.inc
