# Copyright (C) 2015 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1997 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += alloca.c
SRC += cfree.c
SRC += getlongp.c
SRC += getpass.c
SRC += itoa.c
SRC += putenv.c
SRC += random.c
SRC += stkavail.c
SRC += swab.c
SRC += xfree.c
SRC += xmalloc.c
SRC += xrealloc.c
SRC += ecvtbuf.c
SRC += ecvt.c
SRC += fcvtbuf.c
SRC += fcvt.c
SRC += gcvt.c
SRC += rand48.c
#SRC += memalign.c
SRC += valloc.c

include $(TOP)/../makefile.inc
