# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += alloca.c
SRC += cfree.c
SRC += getlongp.c
SRC += getpass.c
SRC += itoa.c
SRC += putenv.c
SRC += random.c
SRC += swab.c
SRC += xfree.c
SRC += xmalloc.c
SRC += xrealloc.c

include $(TOP)/../makefile.inc
