# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += fseeko.c
SRC += fseeko64.c
SRC += ftello.c
SRC += ftello64.c
SRC += mkstemp.c
SRC += mktemp.c
SRC += tempnam.c
SRC += vscanf.c
SRC += vfscanf.S
SRC += vsscanf.c

include $(TOP)/../makefile.inc
