# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += resource.c
SRC += gtrlimit.c
SRC += strlimit.c

include $(TOP)/../makefile.inc
