# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details

TOP=../..

SRC += a64l.c
SRC += l64a.c
SRC += mkdtemp.c
SRC += realpath.c
SRC += unsetenv.c

include $(TOP)/../makefile.inc
