# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += acos.S
SRC += acosh.c
SRC += asin.S
SRC += asinh.c
SRC += atan.S
SRC += atan2.S
SRC += atanh.c
SRC += ceil.S
SRC += cos.S
SRC += cosh.c
SRC += exp.S
SRC += fabs.S
SRC += floor.S
SRC += fmod.S
SRC += frexp.c
SRC += huge_val.c
SRC += hypot.c
SRC += ldexp.c
SRC += log.S
SRC += log10.S
SRC += modf.S
SRC += modfl.S
SRC += pow.S
SRC += pow10.S
SRC += pow2.S
SRC += sin.S
SRC += sinh.c
SRC += sqrt.S
SRC += tan.S
SRC += tanh.c

include $(TOP)/../makefile.inc
