# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += acos.S
SRC += acosh.S
SRC += asin.S
SRC += asinh.S
SRC += atan.S
SRC += atan2.S
SRC += atanh.S
SRC += ceil.S
SRC += cos.S
SRC += cosh.S
SRC += exp.S
SRC += fabs.S
SRC += floor.S
SRC += fmod.S
SRC += frexp.S
SRC += huge_val.c
SRC += hypot.S
SRC += ldexp.S
SRC += log.S
SRC += log10.S
SRC += modf.S
SRC += modfl.S
SRC += pow.S
SRC += pow10.S
SRC += pow2.S
SRC += sin.S
SRC += sinh.S
SRC += sqrt.S
SRC += tan.S
SRC += tanh.S

include $(TOP)/../makefile.inc
