# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += acos.S
AS_SRC += acosh.S
AS_SRC += asin.S
AS_SRC += asinh.S
AS_SRC += atan.S
AS_SRC += atan2.S
AS_SRC += atanh.S
AS_SRC += ceil.S
AS_SRC += cos.S
AS_SRC += cosh.S
AS_SRC += exp.S
AS_SRC += fabs.S
AS_SRC += floor.S
AS_SRC += fmod.S
AS_SRC += frexp.S
#SRC += huge_val.c
SRC += _modfl.c
AS_SRC += hypot.S
AS_SRC += ldexp.S
AS_SRC += log.S
AS_SRC += log10.S
AS_SRC += modf.S
AS_SRC += modfl.S
AS_SRC += pow.S
AS_SRC += pow10.S
AS_SRC += pow2.S
AS_SRC += sin.S
AS_SRC += sinh.S
AS_SRC += sqrt.S
AS_SRC += tan.S
AS_SRC += tanh.S

include $(TOP)/../makefile.inc
