# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += dosexec.c
SRC += spawnl.c
SRC += spawnle.c
SRC += spawnlp.c
SRC += spawnlpe.c
SRC += spawnv.c
SRC += spawnvp.c
SRC += spawnvpe.c

include $(TOP)/../makefile.inc
