# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += _irdlink.c
SRC += basename.c
SRC += dirname.c
SRC += fchown.c
SRC += fsync.c
SRC += ftruncat.c
SRC += getdtabl.c
SRC += gethostn.c
SRC += getpages.c
SRC += getwd.c
SRC += lchown.c
SRC += llseek.c
SRC += lockf.c
SRC += llockf.c
SRC += nice.c
SRC += readlink.c
SRC += sdirlink.c
SRC += symlink.c
SRC += sync.c
SRC += truncate.c
SRC += usleep.c
SRC += vfork.c
SRC += xsymlink.c

include $(TOP)/../makefile.inc
