# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += fsync.c
SRC += ftruncat.c
SRC += getdtabl.c
SRC += gethostn.c
SRC += getpages.c
SRC += getwd.c
SRC += nice.c
SRC += sync.c
SRC += truncate.c
SRC += usleep.c
SRC += vfork.c

include $(TOP)/../makefile.inc
