# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1997 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

# supress all warnings here
CFLAGS = -w

SRC += regcomp.c
SRC += regerror.c
SRC += regexec.c
SRC += regfree.c

include $(TOP)/../makefile.inc

XGCC = $(XLGCC)

