# Copyright (C) 1994 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += float_de.c
SRC += float_dm.c
SRC += float_dx.c
SRC += float_fe.c
SRC += float_fm.c
SRC += float_fx.c
SRC += float_le.c
SRC += float_lm.c
SRC += float_lx.c

include $(TOP)/../makefile.inc
