TOP=../..

SRC += append.c
SRC += bintext.c
SRC += file.c
SRC += fscanf.c
SRC += fseek.c
SRC += hello.c
SRC += mktemp.c
SRC += printf.c
SRC += sscanf.c
SRC += tmpnam.c

include $(TOP)/../makefile.inc
