TOP=../..

SRC += append.c
SRC += bintext.c
SRC += decimal.c
SRC += fflush.c
SRC += filbuf.c
SRC += file.c
SRC += fprintf.c
SRC += fputc.c
SRC += fputs.c
SRC += fscanf.c
SRC += fseek.c
SRC += fseek2.c
SRC += hello.c
SRC += mktemp.c
SRC += printf.c
SRC += printf2.c
SRC += printf3.c
SRC += printf4.c
SRC += printf6.c
SRC += sscanf.c
SRC += sscanf2.c
SRC += sscanf3.c
SRC += tmpnam.c
SRC += tremove.c
SRC += tscanf.c
SRC += tscanf2.c
SRC += tscanf3.c
SRC += tsnprtf.c
SRC += tsnprtf2.c

include $(TOP)/../makefile.inc
