TOP=../..

SRC += append.c
SRC += bintext.c
SRC += fflush.c
SRC += filbuf.c
SRC += file.c
SRC += fprintf.c
SRC += fputc.c
SRC += fputs.c
SRC += fscanf.c
SRC += fseek.c
SRC += fseek2.c
SRC += hello.c
SRC += mktemp.c
SRC += printf.c
SRC += sscanf.c
SRC += tmpnam.c
SRC += tscanf.c
SRC += tsnprtf.c
SRC += tsnprtf2.c

include $(TOP)/../makefile.inc
