# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += itimer.c
SRC += kill.c
SRC += sigactio.c
SRC += sigaddse.c
SRC += sigdelse.c
SRC += sigempty.c
SRC += sigfills.c
SRC += sigismem.c
SRC += sigpendi.c
SRC += sigprocm.c
SRC += sigsuspe.c

include $(TOP)/../makefile.inc
