# Copyright (C) 2015 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += d_close.c
SRC += d_commit.c
SRC += d_creat.c
SRC += d_creatn.c
SRC += d_exterr.c
SRC += d_findf.c
SRC += d_findn.c
SRC += d_getdat.c
SRC += d_getdf.c
SRC += d_getdrv.c
SRC += d_getfa.c
SRC += d_getftm.c
SRC += d_gettim.c
SRC += d_open.c
SRC += d_read.c
SRC += d_setdat.c
SRC += d_setdrv.c
SRC += d_setfa.c
SRC += d_setftm.c
SRC += d_settim.c
SRC += d_strerr.c
SRC += d_write.c

include $(TOP)/../makefile.inc
