# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += cbrt.S
SRC += exp2.S
SRC += exp10.S
SRC += expm1.S
SRC += log1p.S
SRC += log2.S
SRC += powi.S
SRC += sincos.S

include $(TOP)/../makefile.inc
