# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += cbrt.S
AS_SRC += exp2.s
AS_SRC += exp10.s
AS_SRC += expm1.S
AS_SRC += log1p.S
AS_SRC += log2.S
AS_SRC += powi.S
AS_SRC += sincos.S

include $(TOP)/../makefile.inc
