# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2000 DJ Delorie, see COPYING.DJ for details

TOP=..

SRC += open2.c
SRC += pipe.c
SRC += tzero.c

include $(TOP)/../makefile.inc
