# Copyright (C) 1994 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += lconv.c
SRC += mbcurmax.c
SRC += mblen.c
SRC += mbstowcs.c
SRC += mbtowc.c
SRC += setlocal.c
SRC += wcstombs.c
SRC += wctomb.c

include $(TOP)/../makefile.inc
