# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += _chmod.c
SRC += _close.c
SRC += _creat.c
SRC += _creat_n.c
SRC += _open.c
SRC += _read.c
SRC += _write.c
SRC += crlf2nl.c
SRC += dosio.c
SRC += doslk64.c
SRC += doslock.c
SRC += dosunl64.c
SRC += dosunloc.c
SRC += fd_props.c
SRC += fmode.c
SRC += lock.c
SRC += lock64.c
SRC += putpath.c
SRC += setmode.c
SRC += tell.c
SRC += unlock.c
SRC += unlock64.c
SRC += flushdc.c

include $(TOP)/../makefile.inc
