# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += _chmod.c
SRC += _close.c
SRC += _creat.c
SRC += _open.c
SRC += _read.c
SRC += _write.c
SRC += crlf2nl.c
SRC += dosio.c
SRC += doslock.c
SRC += dosunloc.c
SRC += fmode.c
SRC += lock.c
SRC += putpath.c
SRC += setmode.c
SRC += tell.c
SRC += unlock.c
SRC += flushdc.c

include $(TOP)/../makefile.inc
