TOP=../..

SRC += access.c
SRC += append.c
SRC += chdr.c
SRC += gcwd.c
SRC += getpid.c
SRC += sleep.c
SRC += tread.c
SRC += write.c
SRC += t-isatty.c
SRC += t-lseek.c
SRC += t-pwrite.c

include $(TOP)/../makefile.inc
