# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += fstatvfs.c
SRC += statvfs.c

include $(TOP)/../makefile.inc
