# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += findfirs.c
SRC += findnext.c
SRC += fnmerge.c
SRC += fnsplit.c
SRC += ftreewlk.c
SRC += ftw.c
SRC += getdisk.c
SRC += setdisk.c
SRC += srchpath.c

include $(TOP)/../makefile.inc
