# Copyright (C) 2015 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2003 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=..

SRC += dpmiexcp.c
SRC += exceptn.S
SRC += go32cbrk.c
SRC += godefv1.S
SRC += gopint.c
SRC += gopvec.c
SRC += goqmem.c
SRC += gormcb.c
SRC += gormem.c
SRC += gorvec.c
SRC += infostrc.c
SRC += overflow.S

include $(TOP)/../makefile.inc
