# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += _bcopy.S
SRC += fpurge.c
SRC += setenv.c

include $(TOP)/../makefile.inc
