# Copyright (C) 2015 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += cfgtispd.c
SRC += cfgtospd.c
SRC += cfstispd.c
SRC += cfstospd.c
SRC += tcdrain.c
SRC += tcflow.c
SRC += tcflush.c
SRC += tcgetatr.c
SRC += tcsetatr.c
SRC += tcsndbrk.c
SRC += tminit.c
SRC += tmread.c
SRC += tmwrite.c
SRC += tcgetpgr.c
SRC += tcsetpgr.c
SRC += ttyscrn.c
SRC += readhook.c
SRC += writhook.c

include $(TOP)/../makefile.inc
