# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += cfgtispd.c
SRC += cfgtospd.c
SRC += cfstispd.c
SRC += cfstospd.c
SRC += tcdrain.c
SRC += tcflow.c
SRC += tcflush.c
SRC += tcgetatr.c
SRC += tcsetatr.c
SRC += tcsndbrk.c
SRC += tminit.c
SRC += tcgetpgr.c
SRC += tcsetpgr.c

include $(TOP)/../makefile.inc
