TOP=../..

SRC += env.c
SRC += getenv.c
SRC += mbstowcs.c
SRC += shell.c
SRC += strtold.c
SRC += strtold1.c
SRC += strtod.c
SRC += strtod1.c
SRC += system.c
SRC += system2.c
#SRC += tmalloc.c
SRC += wcstombs.c

include $(TOP)/../makefile.inc
