# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += ib.S
SRC += il.S
SRC += inb.S
SRC += inp.S
SRC += inpw.S
SRC += isb.S
SRC += isl.S
SRC += isw.S
SRC += iw.S
SRC += ob.S
SRC += ol.S
SRC += osb.S
SRC += osl.S
SRC += osw.S
SRC += outb.S
SRC += outp.S
SRC += outpw.S
SRC += ow.S

include $(TOP)/../makefile.inc
