# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += ib.S
AS_SRC += il.S
AS_SRC += inb.S
AS_SRC += inp.S
AS_SRC += inpw.S
AS_SRC += isb.S
AS_SRC += isl.S
AS_SRC += isw.S
AS_SRC += iw.S
AS_SRC += ob.S
AS_SRC += ol.S
AS_SRC += osb.S
AS_SRC += osl.S
AS_SRC += osw.S
AS_SRC += outb.S
AS_SRC += outp.S
AS_SRC += outpw.S
AS_SRC += ow.S

include $(TOP)/../makefile.inc
