# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += getkey.c
SRC += getxkey.c
SRC += getxkstr.c
SRC += kbhit.c

include $(TOP)/../makefile.inc
