# Copyright (C) 2001 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += allocfil.c
SRC += clearerr.c
SRC += doprnt.c
SRC += doscan.c
SRC += fclose.c
SRC += feof.c
SRC += ferror.c
SRC += fflush.c
SRC += fgetc.c
SRC += fgetpos.c
SRC += fgets.c
SRC += filbuf.c
SRC += flsbuf.c
SRC += fopen.c
SRC += fprintf.c
SRC += fputc.c
SRC += fputs.c
SRC += fread.c
SRC += freopen.c
SRC += frlist.c
SRC += fscanf.c
SRC += fseek.c
SRC += fsetpos.c
SRC += ftell.c
SRC += fwalk.c
SRC += fwrite.c
SRC += getc.c
SRC += getchar.c
SRC += gets.c
SRC += getw.c
SRC += perror.c
SRC += printf.c
SRC += putc.c
SRC += putchar.c
SRC += puts.c
SRC += putw.c
SRC += remove.c
SRC += rename.c
SRC += _rename.c
SRC += rewind.c
SRC += scanf.c
SRC += setbuf.c
SRC += setbuffe.c
SRC += setlineb.c
SRC += setvbuf.c
SRC += sprintf.c
SRC += sscanf.c
SRC += stdaux.c
SRC += stderr.c
SRC += stdin.c
SRC += stdiohk.c
SRC += stdout.c
SRC += stdprn.c
SRC += tmpfile.c
SRC += tmpnam.c
SRC += ungetc.c
SRC += vfprintf.c
SRC += vprintf.c
SRC += vsprintf.c
SRC += snprintf.c
SRC += vsnprntf.c

include $(TOP)/../makefile.inc
