# Copyright (C) 2015 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2003 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=..

SRC += dxeload.c
SRC += dlerror.c
SRC += dlregsym.c
SRC += dlunregs.c
SRC += dxe3stat.c
SRC += dlopen.c

include $(TOP)/../makefile.inc
