# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += ffs.S
SRC += memccpy.c
STR += memicmp.c
SRC += stpcpy.c
SRC += strcasec.S
SRC += strdup.c
SRC += stricmp.c
SRC += strlwr.c
SRC += strncase.S
SRC += strnicmp.c
SRC += strsep.c
SRC += strupr.c

include $(TOP)/../makefile.inc
