# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=.

LIBNAME=m

include $(TOP)/../makefile.lib
	
clean ::
	$(MISC) rm makefile.sub
