# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += djmd.S
SRC += djmdr.S
SRC += dmg.c
SRC += dmgb.c
SRC += dmgl.c
SRC += dmgw.c
SRC += dmp.c
SRC += dmpb.c
SRC += dmpl.c
SRC += dmpw.c
SRC += md.S
SRC += mdb.S
SRC += mdl.S
SRC += mdw.S

include $(TOP)/../makefile.inc
