# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += djmd.S
AS_SRC += djmdr.S
SRC += dmg.c
SRC += dmgb.c
SRC += dmgl.c
SRC += dmgw.c
SRC += dmp.c
SRC += dmpb.c
SRC += dmpl.c
SRC += dmpw.c
SRC += mda.c
AS_SRC += md.S
AS_SRC += mdb.S
AS_SRC += mdl.S
AS_SRC += mdw.S

include $(TOP)/../makefile.inc
