# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += conio.c
SRC += scattrib.c
SRC += scclear.c
SRC += sccols.c
SRC += scgetc.c
SRC += scgetch.c
SRC += scmode.c
SRC += scputc.c
SRC += scputs.c
SRC += scretr.c
SRC += scrows.c
SRC += scsetc.c
SRC += scupdate.c
SRC += scupdl.c
SRC += scvbell.c

include $(TOP)/../makefile.inc
