TOP ?= ..
PREFIX ?= /usr/local
INSTALL ?= install

all:
	$(MAKE) -C hello
	$(MAKE) -C helloasm
	$(MAKE) -C rmcb

djgpp:
	$(MAKE) -C hello -f makefile.djgpp
	$(MAKE) -C helloasm -f makefile.djgpp
	$(MAKE) -C rmcb -f makefile.djgpp

clean:
	$(MAKE) -C hello clean
	$(MAKE) -C helloasm clean
	$(MAKE) -C rmcb clean

src_install: clean
	for i in `find . -maxdepth 1 -type d ! -path . -printf '%P\n'`; do \
	  $(INSTALL) -d $(DESTDIR)$(PREFIX)/share/doc/dj64/demos/$$i; \
	  $(INSTALL) -m 0644 $$i/* $(DESTDIR)$(PREFIX)/share/doc/dj64/demos/$$i; \
	done

src_uninstall:
	$(RM) -r $(DESTDIR)$(PREFIX)/share/doc/dj64
