# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# -*- makefile -*-

SHELL := bash -o pipefail

CROSS_PREFIX ?= i686-linux-gnu-
CROSS_GCC = $(CC)
# dont trust $(CPP) for that, as clang -E doesn't work as expected
CROSS_CPP = cpp
# for AS objects
CROSS_AS = $(CROSS_PREFIX)as
CROSS_ASAR = $(CROSS_PREFIX)ar
ifeq ($(CROSS_PREFIX_GCC),)
CROSS_ASGCC = $(CC)
else
CROSS_ASGCC = $(CROSS_PREFIX_GCC)gcc
endif
CROSS_ASCPP = $(CPP) -x assembler-with-cpp $(1) | $(CROSS_AS) --32 -
CROSS_ASSTRIP = $(CROSS_PREFIX)strip
