# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details

LIB = $(TOP)/../../lib
PD = $(TOP)/../../parsers
TG = $(PD)/thunk_gen
MP = $(PD)/mkproto.sh
GT = $(PD)/gen_thunks.sh
GA = $(PD)/gen_asms.sh

all :: plt.inc plt_asms.inc
	../makemake.exe
	$(MAKE) -f makefile.sub
	../makemake.exe -2
	$(MAKE) $(LIB)/libdj64.so
	$(MAKE) $(LIB)/libc.a

MAKEFILE_LIB = 1
include $(TOP)/../makefile.inc

ifneq ($(wildcard makefile.oi),)
include makefile.oi
endif
ifneq ($(wildcard makefile.oio),)
include makefile.oio
endif

$(LIB)/lib$(LIBNAME).a : $(LIB)/lib$(LIBNAME).elf.a
	$(OBJCOPY) -O pe-i386 $< $@

thunk_syms.o: thunk_syms.c asm_incs.h
	$(XGCC) -m32 -g0 -c $< $(EXTRA_CFLAGS) -o $@

$(LIB)/lib$(LIBNAME).elf.a : makefile.rfo thunk_syms.o
	@-$(MISC) rm $@
	$(CROSS_AR) q $@ @$^
	$(CROSS_AR) s $@

$(TG):
	$(MAKE) -C $(PD)

crt0/_crt0.o:
	$(MAKE) -C crt0 _crt0.o

asm_incs.h:
	$(GA) 0 $(TOP)/../../include >$@

plt_asms.inc:
	$(GA) 1 $(TOP)/../../include >$@

asym_incs.h:
	$(GA) 2 $(TOP)/../../include >$@

thunk_calls.tmp thunk_asms.tmp thunk_incs.h plt.inc &: \
    $(LIB)/lib$(LIBNAME).elf.a crt0/_crt0.o $(TG)
	$(MP) $< $(TOP)/crt0/_crt0.o $(TOP)/../../include thunk_asms.tmp \
		thunk_calls.tmp plt.inc thunk_incs.h

thunk_calls.h: thunk_calls.tmp
	$(TG) <$< >$@

thunk_asms.h: thunk_asms.tmp
	$(GT) $(TG) $< $(PD) >$@

thunks.o: thunk_calls.h thunk_asms.h thunk_incs.h asym_incs.h

$(LIB)/libdj64.so : $(OBJS) makefile.rf thunk_calls.h thunk_asms.h thunks.o
	$(CROSS_GCC) -shared -Wl,-Bsymbolic -o $@ @makefile.rf thunks.o
	@echo "Have `nm -u $@ | grep "U " | wc -l` undefined symbols"

newlib:
	$(MISC) rm $(LIB)/lib$(LIBNAME).a
	$(CROSS_AR) q $(LIB)/lib$(LIBNAME).a @makefile.rf id_$(LIBNAME).o
	$(CROSS_AR) s $(LIB)/lib$(LIBNAME).a

clean ::
	$(TOP)/../makemake.exe
	$(MAKE) -f makefile.sub SUBARGS=clean
	@-$(MISC) rm makefile.oi makefile.rf makefile.rfo
