# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
all : rmake.exe copyrite.exe

rmake.exe : rmake.cc
	gcc -O2 rmake.cc -o rmake.exe

copyrite.exe : copyrite.cc
	gcc -O2 copyrite.cc -o copyrite.exe
