# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details

LIB = $(TOP)/../../lib

all ::
	../makemake.exe
	$(MAKE) -f makefile.sub
	../makemake.exe -2
	$(MAKE) $(LIB)/lib$(LIBNAME).so
	$(MAKE) $(LIB)/lib$(LIBNAME).a

MAKEFILE_LIB = 1
include $(TOP)/../makefile.inc

OBJS :=
AS_OBJS :=

ifneq ($(wildcard makefile.oi),)
include makefile.oi
endif
ifneq ($(wildcard makefile.oio),)
include makefile.oio
endif

$(LIB)/lib$(LIBNAME).a : $(AS_OBJS) makefile.rfo
	@-$(MISC) rm $@
	$(CROSS_AR) q $(LIB)/lib$(LIBNAME).a @makefile.rfo
	$(CROSS_AR) s $(LIB)/lib$(LIBNAME).a

$(LIB)/lib$(LIBNAME).so : $(OBJS) makefile.rf
	$(CROSS_GCC) -shared -o $@ @makefile.rf

newlib:
	$(MISC) rm $(LIB)/lib$(LIBNAME).a
	$(CROSS_AR) q $(LIB)/lib$(LIBNAME).a @makefile.rf id_$(LIBNAME).o
	$(CROSS_AR) s $(LIB)/lib$(LIBNAME).a

clean ::
	$(TOP)/../makemake.exe
	$(MAKE) -f makefile.sub SUBARGS=clean
	@-$(MISC) rm makefile.oi makefile.rf makefile.rfo
