TOP=../../..

SRC += fixpath.c
SRC += fstat.c
SRC += leak.c
SRC += lstat.c
SRC += mkdir.c
SRC += stat.c
SRC += stat1.c
SRC += svsf.c
SRC += symstat.c
SRC += t-fchmod.c

include $(TOP)/../makefile.inc
