TOP=../..

SRC += ctime.c 		# There's a warning when compiling this with gcc 2.953.
SRC += mktime.c
SRC += strftime.c
SRC += tzinfo.c
SRC += tzinfo2.c
SRC += xstrftm.c	# There's a warning when compiling this with gcc 2.953.

include $(TOP)/../makefile.inc

